development:
  adapter: postgresql
  encoding: unicode
  database: fire_camp_development
  pool: 5
  username: eduardo  
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: fire_camp_test
  pool: 5
  username: eduardo
  password: password
