development:
  adapter: postgresql
  encoding: unicode
  database: project_development
  pool: 5
  username: eduardo  
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: project_test
  pool: 5
  username: eduardo
  password: password
