development:
  adapter: postgresql
  encoding: unicode
  database: market_place_development
  pool: 5
  username: eduardo  
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: market_place_test
  pool: 5
  username: eduardo
  password: password
